[package]
name = "bench2"
description = "a simple Rust benchmarker"
version = "0.3.0"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]

[dependencies]
foropts = { git = "https://github.com/tov/foropts-rs.git" }
